# frozen_string_literal: true

require_relative "./rouge/template"

module Base16
  module Rouge
    class << self
      DEFAULT_TEMPLATE = File.expand_path("../../templates/default.mustache", __dir__)

      def template
        File.open(DEFAULT_TEMPLATE, "w") do |file|
          file.write <<~HEADER
          /*
             base16-rouge (https://github.com/skipkayhil/base16-rouge)
             by Hartley McGuire (https://github.com/skipkayhil)
             based on CSS generated by Rouge (https://github.com/rouge-ruby/rouge)
             {{ scheme-name }} by {{ scheme-author }}
          */
          HEADER
          file.write(mustache_template)
          file.write("\n")
        end
      end

      private

      def mustache_template
        Template.render(scope: ".highlight")
      end
    end
  end
end
